<template>
    <v-row
      id="student_index"
      align="center"
      justify="center"
    >
      <v-col
        cols="12"
        sm="5"
        md="5"
        lg="5"
      >
        <v-sheet
            color="white"
        >
            123
        </v-sheet>
      </v-col>

      <v-col
        cols="12"
        sm="7"
        md="7"
        lg="7"
      >
        <v-sheet
            color="white"
        >
            123
        </v-sheet>
      </v-col>
    </v-row>
</template>
